import logging
from typing import Any

from langgraph.graph import END, START, StateGraph

from app.service.k8s_service import K8sService
from app.service.s3_service import S3Service
from app.workflow.state import SessionAnalyzerState

logger = logging.getLogger(__name__)


async def create_k8s_job(state: SessionAnalyzerState) -> dict:
    """Create the K8s Job for session-based analysis."""
    k8s = K8sService()
    job_name = k8s.create_session_analyzer_job(
        session_id=state["session_id"],
        iteration_index=state["iteration_index"],
        repo_url=state["repo_url"],
        branch=state["branch"],
        instruction=state["instruction"],
        num_proposals=state["num_proposals"],
        selected_proposal_index=state.get("selected_proposal_index"),
    )
    return {"k8s_job_name": job_name, "status": "running"}


async def wait_for_job(state: SessionAnalyzerState) -> dict:
    """Poll K8s Job until completion."""
    k8s = K8sService()
    k8s_job_name = state["k8s_job_name"]
    assert k8s_job_name is not None
    result = await k8s.wait_for_job(k8s_job_name)

    if result == "succeeded":
        return {"status": "succeeded"}

    logs = k8s.get_job_logs(k8s_job_name)
    error_msg = f"Analyzer job {result}."
    if logs:
        error_msg += f" Logs: {logs[:500]}"
    return {"status": "failed", "error": error_msg}


async def extract_results(state: SessionAnalyzerState) -> dict:
    """Read analysis results from S3."""
    s3 = S3Service()
    session_id = state["session_id"]
    iteration_index = state["iteration_index"]

    proposals = s3.get_proposals(session_id, iteration_index)
    before_key = s3.before_screenshot_key(session_id, iteration_index)
    has_before = s3.exists(before_key)

    if proposals is None:
        return {"error": "Failed to read proposals from S3", "status": "failed"}
    if len(proposals) == 0:
        return {"error": "No proposals generated by analyzer", "status": "failed"}
    return {
        "proposals": proposals,
        "before_screenshot_key": before_key if has_before else None,
    }


def route_after_wait(state: SessionAnalyzerState) -> str:
    """Route based on job completion status."""
    if state["status"] == "succeeded":
        return "extract_results"
    return END


def build_session_analyzer_graph() -> Any:
    """Build and compile the session-based analyzer LangGraph."""
    graph = StateGraph(SessionAnalyzerState)

    graph.add_node("create_k8s_job", create_k8s_job)
    graph.add_node("wait_for_job", wait_for_job)
    graph.add_node("extract_results", extract_results)

    graph.add_edge(START, "create_k8s_job")
    graph.add_edge("create_k8s_job", "wait_for_job")
    graph.add_conditional_edges(
        "wait_for_job",
        route_after_wait,
        {"extract_results": "extract_results", END: END},
    )
    graph.add_edge("extract_results", END)

    return graph.compile()
