from typing import Protocol
from uuid import UUID

from app.model.session import (
    Iteration,
    IterationStatus,
    Proposal,
    ProposalStatus,
    Session,
    SessionStatus,
    Setting,
)


class SessionRepositoryProtocol(Protocol):
    def create(self, session: Session) -> Session: ...
    def get_by_id(self, session_id: UUID) -> Session | None: ...
    def update_status(self, session_id: UUID, status: SessionStatus) -> Session | None: ...
    def list_all(self) -> list[Session]: ...


class IterationRepositoryProtocol(Protocol):
    def create(self, iteration: Iteration) -> Iteration: ...
    def get_by_id(self, iteration_id: UUID) -> Iteration | None: ...
    def get_by_session_and_index(
        self, session_id: UUID, iteration_index: int
    ) -> Iteration | None: ...
    def get_latest_for_session(self, session_id: UUID) -> Iteration | None: ...
    def get_all_for_session(self, session_id: UUID) -> list[Iteration]: ...
    def update_status_optimistic(
        self,
        iteration_id: UUID,
        expected_version: int,
        status: IterationStatus,
        **kwargs: object,
    ) -> Iteration | None: ...
    def update_selected_proposal(
        self, iteration_id: UUID, proposal_index: int
    ) -> Iteration | None: ...


class ProposalRepositoryProtocol(Protocol):
    def create(self, proposal: Proposal) -> Proposal: ...
    def get_by_id(self, proposal_id: UUID) -> Proposal | None: ...
    def get_by_iteration_and_index(
        self, iteration_id: UUID, proposal_index: int
    ) -> Proposal | None: ...
    def get_all_by_status(self, status: ProposalStatus) -> list[Proposal]: ...
    def get_all_for_iteration(self, iteration_id: UUID) -> list[Proposal]: ...
    def update_status_optimistic(
        self,
        proposal_id: UUID,
        expected_version: int,
        status: ProposalStatus,
        **kwargs: object,
    ) -> Proposal | None: ...


class SettingRepositoryProtocol(Protocol):
    def get_by_key(self, key: str) -> Setting | None: ...
    def upsert(self, key: str, value: str) -> Setting: ...
    def list_all(self) -> list[Setting]: ...
    def delete(self, key: str) -> bool: ...
