kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: ui-recommender
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 30000
        hostPort: 30000
        protocol: TCP
    kubeadmConfigPatches:
      - |
        kind: InitConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "ingress-ready=true"
    extraMounts:
      - hostPath: /tmp/ui-recommender-artifacts
        containerPath: /artifacts
  - role: worker
    extraMounts:
      - hostPath: /tmp/ui-recommender-artifacts
        containerPath: /artifacts
  - role: worker
    extraMounts:
      - hostPath: /tmp/ui-recommender-artifacts
        containerPath: /artifacts
