"""add job proposal setting tables

Revision ID: 199f015d6e7d
Revises: 
Create Date: 2026-02-16 15:53:24.976191

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '199f015d6e7d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ANALYZING', 'ANALYZED', 'IMPLEMENTING', 'COMPLETED', 'FAILED', name='jobstatus'), nullable=False),
    sa.Column('repo_url', sa.String(length=500), nullable=False),
    sa.Column('branch', sa.String(length=200), nullable=False),
    sa.Column('instruction', sa.Text(), nullable=False),
    sa.Column('before_screenshot_path', sa.String(length=500), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('k8s_job_name', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('settings',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('proposals',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('proposal_index', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('concept', sa.Text(), nullable=False),
    sa.Column('plan', sa.Text(), nullable=False),
    sa.Column('files', sa.Text(), nullable=True),
    sa.Column('complexity', sa.String(length=20), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'IMPLEMENTING', 'COMPLETED', 'FAILED', name='proposalstatus'), nullable=False),
    sa.Column('after_screenshot_path', sa.String(length=500), nullable=True),
    sa.Column('diff_path', sa.String(length=500), nullable=True),
    sa.Column('k8s_job_name', sa.String(length=200), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('proposals')
    op.drop_table('settings')
    op.drop_table('jobs')
    # ### end Alembic commands ###
